[package]
name = "buldak"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
chrono = "0.4.42"
rusqlite = { version = "0.37.0", features = ["bundled","chrono"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"